version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 3

  status-server:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

# Uncomment the following lines when the Dockerfile for the frontend is ready
#  status-client:
#    build:
#      context: ./Frontend
#      dockerfile: Dockerfile
#    ports:
#      - "4200:80"
#    depends_on:
#      status-server:
#        condition: service_healthy
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
