services:
  service-registry:
    image: markusf01/tevs-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    build:
      context: ./Backend/service_registry
      dockerfile: ../Dockerfile

  api-gateway:
    image: markusf01/tevs-gateway
    ports:
      - "8080:8080"
    environment:
      - service-registry.route=service-registry:8761
    depends_on:
      service-registry:
        condition: service_healthy
    build:
      context: ./Backend/gateway
      dockerfile: ../Dockerfile

  node:
    image: markusf01/tevs-node
    environment:
      - service-registry.route=service-registry:8761
      - api-gateway.route=api-gateway:8080
      - rabbitmq.route=rabbitmq
    depends_on:
      service-registry:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    build:
      context: ./Backend/node
      dockerfile: ./Dockerfile

  status-client:
    image: markusf01/tevs-status-client
    ports:
      - "4200:80"
    depends_on:
      api-gateway:
        condition: service_started
    build:
      context: ./Frontend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" # FE
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pw