services:
  status-server:
    image: status-server
    ports:
      - "8080:8080"
    build:
      context: ./Backend

  status-client:
    image: status-client
    ports:
      - "4200:80"
    depends_on:
      status-server:
        condition: service_started
    build:
      context: ./Frontend