server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: registry-route
          uri: http://${service-registry.route}
          predicates:
            - Path=/eureka/**
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://${service-registry.route}/eureka/
service-registry:
  route: localhost:8761